//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Data.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataEntities : DbContext
    {
        public DataEntities()
            : base("name=DataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<userclaim> userclaims { get; set; }
        public virtual DbSet<userlogin> userlogins { get; set; }
        public virtual DbSet<userrole> userroles { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<director> directors { get; set; }
        public virtual DbSet<movie> movies { get; set; }
        public virtual DbSet<directorGenre> directorGenres { get; set; }
        public virtual DbSet<directorMovie> directorMovies { get; set; }
        public virtual DbSet<movieDirector> movieDirectors { get; set; }
        public virtual DbSet<movieGenre> movieGenres { get; set; }
    }
}
