//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public string movie_name { get; set; }
        public Nullable<System.DateTime> operationTime { get; set; }
        public string operationType { get; set; }
        public string user_name { get; set; }
    
        public virtual user user { get; set; }
        public virtual movie movie { get; set; }
    }
}
