//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class device
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public device()
        {
            this.histories = new HashSet<history>();
            this.device_user = new HashSet<device_user>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string type_1 { get; set; }
        public string type_2 { get; set; }
        public string type_3 { get; set; }
        public string in_time { get; set; }
        public string desc { get; set; }
        public Nullable<sbyte> status { get; set; }
        public Nullable<sbyte> is_safety { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<history> histories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<device_user> device_user { get; set; }
    }
}
