//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class history
    {
        public int id { get; set; }
        public int device_id { get; set; }
        public string user_id { get; set; }
        public sbyte type { get; set; }
        public string time { get; set; }
    
        public virtual device device { get; set; }
        public virtual user user { get; set; }
    }
}
